/**
 *
 */
package com.riversoft.dtask.tasks;

import org.apache.tools.ant.BuildException;

import java.io.*;
import java.util.Properties;

public class TaskUtil {

    public static void copyFile(File from, File to) throws IOException {
        if (from == null)
            throw new IOException("\"from\" refers to null");
        if (to == null)
            throw new IOException("\"to\" refers to null");

        if (!to.exists())
            to.createNewFile();
        if (!from.exists())
            throw new FileNotFoundException("File not found:" + from.getAbsolutePath());

        FileReader fr = new FileReader(from);
        FileWriter fw = new FileWriter(to);

        char[] cbuf = new char[1024];
        int charsRead = 0;
        while ((charsRead = fr.read(cbuf)) != -1) {
            fw.write(cbuf, 0, charsRead);
        }
        fw.close();
        fr.close();
    }

    public static void loadProperties(File f, Properties p) {
        if (f == null) {
            return;
        }

        FileInputStream fis = null;
        try {
            fis = new FileInputStream(f);

            // Use plain Property files
            p.load(fis);
        } catch (FileNotFoundException e) {
            // IS OK, file will be created later
        } catch (Exception e) {
            // Probably not good
            throw new BuildException(e);
        } finally {
            if (fis != null) {
                try {
                    fis.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    /**
     * Saves the Task properties to file
     */
    public static void saveProperties(File f, Properties p) {
        FileOutputStream fos = null;
        try {
            fos = new FileOutputStream(f);

            // Use plain Property files
            p.store(fos, String.format("Auto-generated by Drutt Installer"));
        } catch (Exception e) {
            throw new BuildException("Was unable to save properties to: " + f.getAbsolutePath());
        } finally {
            if (fos != null) {
                try {
                    fos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }
}
