alter table ACT_GE_BYTEARRAY drop CONSTRAINT ACT_FK_BYTEARR_DEPL;
alter table ACT_RU_EXECUTION drop CONSTRAINT ACT_FK_EXE_PROCDEF;
alter table ACT_RU_IDENTITYLINK  drop CONSTRAINT ACT_FK_ATHRZ_PROCEDEF;
alter table ACT_RU_TASK drop CONSTRAINT ACT_FK_TASK_PROCDEF;
alter table ACT_RE_MODEL drop CONSTRAINT ACT_FK_MODEL_SOURCE;
alter table ACT_RE_MODEL drop CONSTRAINT ACT_FK_MODEL_SOURCE_EXTRA;
alter table ACT_RE_MODEL drop CONSTRAINT ACT_FK_MODEL_DEPLOYMENT;